Repository Team-Mercury-s-Final-Project/Star-BE, pull requests merged in 2025-01, with the labels that each got.

#3 Feat/#1 프로젝트 초기 설정
  .gitattributes
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mercury/star_be/StarBeApplication.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/repository/StudyGroupRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/test/java/com/mercury/star_be/StarBeApplicationTests.java
Labels: feat

#8 infra : backend ci/cd test
  .github/workflows/application.yml
Labels: infra

#12 Feat/#7 공통 응답 객체 및 에러 처리
  build.gradle
  src/main/java/com/mercury/star_be/global/common/ApiResponse.java
  src/main/java/com/mercury/star_be/global/config/SecurityConfig.java
  src/main/java/com/mercury/star_be/global/config/WebConfig.java
  src/main/java/com/mercury/star_be/global/error/BusinessException.java
  src/main/java/com/mercury/star_be/global/error/ErrorResponse.java
  src/main/java/com/mercury/star_be/global/error/GlobalExceptionHandler.java
  src/main/java/com/mercury/star_be/global/error/code/ErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupCreateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupCreateResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/GroupMember.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/java/com/mercury/star_be/user/entity/User.java
Labels: feat

#14 refactor: ErrorCode 수정
  src/main/java/com/mercury/star_be/global/error/GlobalExceptionHandler.java
  src/main/java/com/mercury/star_be/global/error/code/CommonErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/ErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
Labels: refactoring

#17 Feat/#7 RestDocs 적용
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/mercury/star_be/global/config/SecurityConfig.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupCreateRequest.java
  src/main/resources/static/docs/index.html
  src/test/java/com/mercury/star_be/common/RestDocsConfiguration.java
  src/test/java/com/mercury/star_be/common/RestDocsTestSupport.java
  src/test/java/com/mercury/star_be/studygroup/StudyGroupIntegrationTest.java
Labels: test

#23 Feat/#19 스터디 그룹 조회 및 수정 기능
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupCreateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupUpdateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupDetailResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupUpdateResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/resources/static/docs/index.html
  src/test/java/com/mercury/star_be/common/DatabaseCleanup.java
  src/test/java/com/mercury/star_be/common/RestDocsTestSupport.java
  src/test/java/com/mercury/star_be/studygroup/StudyGroupIntegrationTest.java
Labels: feat

#32 Feat/#20 SSE를 사용한 스터디 그룹원 정보 전송
  build.gradle
  src/main/java/com/mercury/star_be/global/config/RedisConfig.java
  src/main/java/com/mercury/star_be/global/config/SecurityConfig.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupSseController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupCreateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupUpdateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/GroupMemberSseResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/MemberStatusSseResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/ConnectionStatus.java
  src/main/java/com/mercury/star_be/studygroup/entity/GroupMember.java
  src/main/java/com/mercury/star_be/studygroup/repository/GroupMemberRepository.java
  src/main/java/com/mercury/star_be/studygroup/repository/SseEmitterRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseServiceImpl.java
Labels: feat

#33 test: 테스트 컨테이너 제거
  build.gradle
  src/test/java/com/mercury/star_be/common/RestDocsTestSupport.java
Labels: test

#34 그룹 리스트 완료
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/docs/asciidoc/index.adoc
  src/main/java/com/mercury/star_be/global/config/QueryDSLConfig.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/PaginationResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupListResponse.java
  src/main/java/com/mercury/star_be/studygroup/repository/StudyGroupCustomRepository.java
  src/main/java/com/mercury/star_be/studygroup/repository/StudyGroupCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/studygroup/repository/StudyGroupRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/resources/static/docs/index.html
  src/test/java/com/mercury/star_be/fixture/StudyGroupFixture.java
  src/test/java/com/mercury/star_be/studygroup/StudyGroupIntegrationTest.java
Labels: feat, docs, test

#39 그룹 페이지 가입하기 완료
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/entity/GroupMember.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/repository/GroupMemberRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/java/com/mercury/star_be/user/controller/UserController.java
  src/main/java/com/mercury/star_be/user/dto/request/UserRequest.java
  src/main/java/com/mercury/star_be/user/dto/response/UserResponse.java
  src/main/java/com/mercury/star_be/user/entity/User.java
  src/main/java/com/mercury/star_be/user/repository/UserRepository.java
  src/main/java/com/mercury/star_be/user/service/UserService.java
  src/main/java/com/mercury/star_be/user/service/UserServiceImpl.java
Labels: feat

#43 Hotfix/그룹조회수정
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupDetailResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupListResponse.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/resources/static/docs/index.html
Labels: refactoring

#44 feat: 공지사항 생성 수정 삭제 완성 테스트 코드는 미완성
  src/main/java/com/mercury/star_be/global/error/code/NoticeErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/controller/NoticeController.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/NoticeCreateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/NoticeUpdateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeCreateResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeUpdateResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/Notice.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeService.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeServiceImpl.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
Labels: feat

#48 feat: 사용자 그룹 닉네임 변경
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/ChangeGroupNicknameRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/ChangeGroupNicknameResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/GroupMember.java
  src/main/java/com/mercury/star_be/studygroup/repository/GroupMemberRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/test/java/com/mercury/star_be/fixture/StudyGroupFixture.java
  src/test/java/com/mercury/star_be/studygroup/StudyGroupIntegrationTest.java
Labels: feat

#49 Feat/#46 이미지 업로드
  src/main/java/com/mercury/star_be/file/controller/FileController.java
  src/main/java/com/mercury/star_be/file/dto/response/ImageUploadResponse.java
  src/main/java/com/mercury/star_be/file/service/FileService.java
  src/main/java/com/mercury/star_be/file/service/GcsFileServiceImpl.java
  src/main/java/com/mercury/star_be/global/error/code/FileErrorCode.java
Labels: feat

#50 Feat/#47 공지사항 조회 & 목록 조회
  src/main/java/com/mercury/star_be/studygroup/controller/NoticeController.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeResponse.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeCustomRepository.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeService.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeServiceImpl.java
Labels: feat

#52 Feat/ouath2&jwt
  build.gradle
  src/main/java/com/mercury/star_be/file/controller/FileController.java
  src/main/java/com/mercury/star_be/file/dto/response/ImageUploadResponse.java
  src/main/java/com/mercury/star_be/file/service/FileService.java
  src/main/java/com/mercury/star_be/file/service/GcsFileServiceImpl.java
  src/main/java/com/mercury/star_be/global/config/SecurityConfig.java
  src/main/java/com/mercury/star_be/global/config/WebConfig.java
  src/main/java/com/mercury/star_be/global/config/WebSocketBrokerConfiguration.java
  src/main/java/com/mercury/star_be/global/error/GlobalExceptionHandler.java
  src/main/java/com/mercury/star_be/global/error/code/AuthenticationErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/FileErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/NoticeErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/global/error/code/UserErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/controller/NoticeController.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/ChangeGroupNicknameRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/NoticeCreateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/NoticeUpdateRequest.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/ChangeGroupNicknameResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeCreateResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeUpdateResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupDetailResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupListResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/GroupMember.java
  src/main/java/com/mercury/star_be/studygroup/entity/Notice.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/repository/GroupMemberRepository.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeCustomRepository.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeService.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeServiceImpl.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/java/com/mercury/star_be/user/Handler/CustomSuccessHandler.java
  src/main/java/com/mercury/star_be/user/controller/ImageUploadController.java
  src/main/java/com/mercury/star_be/user/controller/UserController.java
  src/main/java/com/mercury/star_be/user/dto/response/GoogleResponse.java
  src/main/java/com/mercury/star_be/user/dto/response/NaverResponse.java
  src/main/java/com/mercury/star_be/user/dto/response/Oauth2Response.java
  src/main/java/com/mercury/star_be/user/dto/response/UserResponse.java
  src/main/java/com/mercury/star_be/user/dto/response/kakaoResponse.java
  src/main/java/com/mercury/star_be/user/entity/User.java
  src/main/java/com/mercury/star_be/user/repository/UserRepository.java
  src/main/java/com/mercury/star_be/user/service/UserService.java
  src/main/java/com/mercury/star_be/user/service/UserServiceImpl.java
  src/main/java/com/mercury/star_be/user/util/CookieUtil.java
  src/main/java/com/mercury/star_be/user/util/JwtFilter.java
  src/main/java/com/mercury/star_be/user/util/JwtUtil.java
  src/main/resources/static/docs/index.html
  src/main/resources/static/fileupload/04ee545d-d09a-4449-a027-a7df2d74a9f7_1.png
  src/main/resources/static/fileupload/27a75abd-5623-4df6-8941-3673e702b006_1.png
  src/main/resources/static/fileupload/582f6c8a-57ac-4c60-abf1-f99da79a2394_1.png
  src/main/resources/static/fileupload/ae908a35-343a-443a-8ccc-d2ed879896ea_면접사진.jpg
  src/main/resources/static/fileupload/fa966b5b-efa9-494a-b967-64a58d46cb00_%EB%A9%B4%EC%A0%91%EC%82%AC%EC%A7%84.jpg
  src/test/java/com/mercury/star_be/fixture/StudyGroupFixture.java
  src/test/java/com/mercury/star_be/studygroup/StudyGroupIntegrationTest.java
Labels: feat
