Repository Team-Mercury-s-Final-Project/Star-BE, pull requests merged in 2025-02, with the labels that each got.

#56 refactor: token 받아오는걸로 변경 및 비밀번호 입력 추가
  src/main/java/com/mercury/star_be/global/config/SecurityConfig.java
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/controller/NoticeController.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/request/StudyGroupJoinRequest.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeService.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeServiceImpl.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/resources/static/docs/index.html
Labels: refactoring

#59 Feat/#58 사용자 채팅 차단 & 차단 해제
  src/main/java/com/mercury/star_be/global/config/SecurityConfig.java
  src/main/java/com/mercury/star_be/global/error/code/UserErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/user/controller/UserController.java
  src/main/java/com/mercury/star_be/user/dto/request/UserBlockRequest.java
  src/main/java/com/mercury/star_be/user/dto/request/UserUnblockRequest.java
  src/main/java/com/mercury/star_be/user/dto/response/BlockUserListResponse.java
  src/main/java/com/mercury/star_be/user/entity/BlockUser.java
  src/main/java/com/mercury/star_be/user/entity/User.java
  src/main/java/com/mercury/star_be/user/repository/BlockUserCustomRepository.java
  src/main/java/com/mercury/star_be/user/repository/BlockUserCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/user/repository/BlockUserRepository.java
  src/main/java/com/mercury/star_be/user/service/BlockUserService.java
  src/main/java/com/mercury/star_be/user/service/BlockUserServiceImpl.java
  src/main/java/com/mercury/star_be/user/service/UserService.java
  src/main/java/com/mercury/star_be/user/service/UserServiceImpl.java
  src/main/resources/static/docs/index.html
Labels: feat

#65 Hotfix/token and response
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeCreateResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/NoticeUpdateResponse.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeServiceImpl.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
Labels: fix, refactoring

#67 queryDSL 사용해서 반환함
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/MyStudyGroupListResponse.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupDetailResponse.java
  src/main/java/com/mercury/star_be/studygroup/repository/StudyGroupCustomRepository.java
  src/main/java/com/mercury/star_be/studygroup/repository/StudyGroupCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/resources/static/docs/index.html
Labels: feat

#72 Feat/#62 그룹 sse 실시간 상태 조회
  build.gradle
  src/main/java/com/mercury/star_be/StarBeApplication.java
  src/main/java/com/mercury/star_be/global/error/GlobalExceptionHandler.java
  src/main/java/com/mercury/star_be/global/error/code/CommonErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupSseController.java
  src/main/java/com/mercury/star_be/studygroup/repository/SseEmitterRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseServiceImpl.java
Labels: feat

#75 feat: 그룹에 들어가는 로직 작성 testcode 미작성
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/StudyGroupEnterResponse.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
Labels: feat

#80 fix: sse 연결 버그 수정
  src/main/java/com/mercury/star_be/studygroup/repository/SseEmitterRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseServiceImpl.java
Labels: fix

#87 fix: redis sessionId remove 방식 변경
  src/main/java/com/mercury/star_be/global/common/WebSocketEventListener.java
Labels: fix

#88 Feat/#82 그룹 가입 시 그룹채팅방 생성 기능 연결
  src/main/java/com/mercury/star_be/chat/entity/ChatRoom.java
  src/main/java/com/mercury/star_be/studygroup/controller/StudyGroupController.java
  src/main/java/com/mercury/star_be/studygroup/entity/GroupMember.java
  src/main/java/com/mercury/star_be/studygroup/entity/StudyGroup.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
  src/main/java/com/mercury/star_be/user/controller/UserController.java
Labels: feat

#96 Feat/#92 집중방 입장 시 실시간 상태 변경
  src/main/java/com/mercury/star_be/global/common/WebSocketEventListener.java
  src/main/java/com/mercury/star_be/studygroup/entity/ConnectionStatus.java
  src/main/java/com/mercury/star_be/studygroup/entity/Notice.java
  src/main/java/com/mercury/star_be/studygroup/repository/GroupMemberCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/studygroup/repository/NoticeCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/studygroup/repository/SseEmitterRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/NoticeServiceImpl.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseServiceImpl.java
  src/main/java/com/mercury/star_be/timer/service/TimerServiceImpl.java
Labels: feat

#99 refacror/#내정보페이지기능수정
  src/main/java/com/mercury/star_be/global/config/WebSocketBrokerConfiguration.java
  src/main/java/com/mercury/star_be/studygroup/dto/response/GroupMembeResponse.java
  src/main/java/com/mercury/star_be/user/controller/UserController.java
  src/main/java/com/mercury/star_be/user/repository/BlockUserCustomRepositoryImpl.java
  src/main/java/com/mercury/star_be/user/repository/BlockUserRepository.java
  src/main/java/com/mercury/star_be/user/service/BlockUserService.java
  src/main/java/com/mercury/star_be/user/service/BlockUserServiceImpl.java
  src/main/java/com/mercury/star_be/user/service/UserService.java
  src/main/java/com/mercury/star_be/user/service/UserServiceImpl.java
  src/main/java/com/mercury/star_be/user/util/CookieUtil.java
  src/main/java/com/mercury/star_be/user/util/JwtFilter.java
Labels: feat, refactoring

#101 feat: 그룹 가입 시 그룹채팅방 가입
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupServiceImpl.java
Labels: feat

#117 feat/#112 rabbitmq를 사용한 sse 다중서버 처리
  src/main/java/com/mercury/star_be/chat/controller/ChatController.java
  src/main/java/com/mercury/star_be/global/config/RabbitMQConfig.java
  src/main/java/com/mercury/star_be/global/error/code/StudyGroupErrorCode.java
  src/main/java/com/mercury/star_be/studygroup/dto/SseQueueMessage.java
  src/main/java/com/mercury/star_be/studygroup/repository/SseEmitterRepository.java
  src/main/java/com/mercury/star_be/studygroup/service/SseRabbitMQListener.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseService.java
  src/main/java/com/mercury/star_be/studygroup/service/StudyGroupSseServiceImpl.java
Labels: feat

#120 refactor: 처음 그룹원 타이머 데이터 불러올 때 밀리초 단위로 보정
  src/main/java/com/mercury/star_be/timer/dto/TimerDto.java
  src/main/java/com/mercury/star_be/timer/entity/Timer.java
  src/main/java/com/mercury/star_be/timer/service/TimerServiceImpl.java
Labels: refactoring
